# Generated by Django 3.1.4 on 2021-01-12 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20210112_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
