# Generated by Django 3.1.4 on 2021-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_answer_downvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
