# Generated by Django 3.1.4 on 2021-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210116_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
